/**
 * Drizzle ORM Schema for FiveM Server Tracker
 *
 * Defines the four core tables for the tiered data retention strategy:
 * - `servers`: Canonical server records, upserted each poll cycle
 * - `snapshots`: Raw per-server-per-poll data, retained 7 days
 * - `hourlyRollups`: Hourly aggregates from snapshots, retained 90 days
 * - `dailyRollups`: Daily aggregates from hourly rollups, retained indefinitely
 *
 * All timestamps are stored as integer Unix epochs (seconds) using Drizzle's
 * `{ mode: 'timestamp' }` for efficient range queries and indexing.
 */

import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core';

/**
 * Canonical server record, upserted on each poll cycle.
 *
 * Each FiveM server has a unique endpoint ID (e.g., "bkr4qr") that serves
 * as the primary key. Server metadata is updated every poll; historical
 * player counts are tracked via the snapshots table.
 */
export const servers = sqliteTable('servers', {
  /** FiveM endpoint ID (e.g., "bkr4qr") - unique identifier from the master list */
  id: text('id').primaryKey(),

  /** Raw hostname with FiveM color codes and formatting intact */
  hostname: text('hostname').notNull(),

  /** Sanitized hostname with all color codes, tilde tags, and Unicode anomalies stripped */
  hostnameClean: text('hostname_clean').notNull(),

  /** Project name from sv_projectName server variable */
  projectName: text('project_name'),

  /** Project description from sv_projectDesc server variable */
  projectDescription: text('project_description'),

  /** Game type / gamemode (e.g., "roleplay", "racing") */
  gametype: text('gametype'),

  /** Current map name */
  mapname: text('mapname'),

  /** Maximum player slots configured on the server */
  maxPlayers: integer('max_players').notNull(),

  /** Denormalized current player count, updated each poll cycle to avoid N+1 queries on listing */
  currentPlayers: integer('current_players').notNull().default(0),

  /** Server icon version number for constructing CDN icon URLs, null if no icon */
  iconVersion: integer('icon_version'),

  /** Server locale code (e.g., "en-US", "es-ES") */
  locale: text('locale'),

  /** JSON-serialized array of server tags for categorization */
  tags: text('tags'),

  /** JSON-serialized array of running resources/scripts */
  resources: text('resources'),

  /** Whether the server is currently considered online (uses hysteresis) */
  isOnline: integer('is_online', { mode: 'boolean' }).notNull().default(true),

  /**
   * Number of consecutive polls where this server was not found in the stream.
   * Used for hysteresis: server is marked offline only after exceeding the
   * OFFLINE_THRESHOLD (default 3 = 45 minutes of missed polls).
   */
  consecutiveMisses: integer('consecutive_misses').notNull().default(0),

  /** Timestamp of the last poll where this server was found in the stream */
  lastSeenAt: integer('last_seen_at', { mode: 'timestamp' }).notNull(),

  /** Timestamp when this server was first discovered */
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),

  /** Timestamp of the most recent update to this server record */
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});

/**
 * Raw snapshot: one row per server per poll cycle.
 *
 * Captures the player count at each 15-minute polling interval. These are
 * the highest-resolution data points and are retained for 7 days before
 * being aggregated into hourly rollups and purged.
 */
export const snapshots = sqliteTable('snapshots', {
  /** Auto-incrementing primary key */
  id: integer('id').primaryKey({ autoIncrement: true }),

  /** Foreign key to the servers table - identifies which server this snapshot belongs to */
  serverId: text('server_id').notNull().references(() => servers.id),

  /** Number of players online at the time of this snapshot */
  playerCount: integer('player_count').notNull(),

  /** Maximum player slots at the time of this snapshot */
  maxPlayers: integer('max_players').notNull(),

  /** Timestamp when this snapshot was taken (poll time) */
  timestamp: integer('timestamp', { mode: 'timestamp' }).notNull(),
}, (table) => [
  /** Composite index for querying snapshots by server within a time range */
  index('idx_snapshots_server_time').on(table.serverId, table.timestamp),

  /** Index for time-based cleanup queries (purging data older than 7 days) */
  index('idx_snapshots_timestamp').on(table.timestamp),
]);

/**
 * Hourly rollup: aggregated statistics from raw snapshots.
 *
 * Generated by aggregating all snapshots within each hour for each server.
 * Provides avg/max/min player counts and sample count. Retained for 90 days
 * before being aggregated into daily rollups and purged.
 */
export const hourlyRollups = sqliteTable('hourly_rollups', {
  /** Auto-incrementing primary key */
  id: integer('id').primaryKey({ autoIncrement: true }),

  /** Foreign key to the servers table */
  serverId: text('server_id').notNull().references(() => servers.id),

  /** Timestamp representing the start of the hour (truncated to hour boundary) */
  hourTimestamp: integer('hour_timestamp', { mode: 'timestamp' }).notNull(),

  /** Average player count across all snapshots in this hour */
  avgPlayers: real('avg_players').notNull(),

  /** Maximum player count observed in any snapshot during this hour */
  maxPlayers: integer('max_players').notNull(),

  /** Minimum player count observed in any snapshot during this hour */
  minPlayers: integer('min_players').notNull(),

  /** Number of snapshots that were aggregated into this rollup */
  sampleCount: integer('sample_count').notNull(),
}, (table) => [
  /** Composite index for querying hourly rollups by server within a time range */
  index('idx_hourly_server_time').on(table.serverId, table.hourTimestamp),
]);

/**
 * Daily rollup: aggregated statistics from hourly rollups.
 *
 * Generated by aggregating all hourly rollups within each day for each server.
 * Provides avg/max/min player counts and sample count. Retained indefinitely
 * to support long-term historical trend analysis.
 */
export const dailyRollups = sqliteTable('daily_rollups', {
  /** Auto-incrementing primary key */
  id: integer('id').primaryKey({ autoIncrement: true }),

  /** Foreign key to the servers table */
  serverId: text('server_id').notNull().references(() => servers.id),

  /** Timestamp representing the start of the day (truncated to day boundary) */
  dayTimestamp: integer('day_timestamp', { mode: 'timestamp' }).notNull(),

  /** Average player count across all hourly rollups for this day */
  avgPlayers: real('avg_players').notNull(),

  /** Maximum player count observed in any hourly rollup during this day */
  maxPlayers: integer('max_players').notNull(),

  /** Minimum player count observed in any hourly rollup during this day */
  minPlayers: integer('min_players').notNull(),

  /** Number of hourly rollups that were aggregated into this daily rollup */
  sampleCount: integer('sample_count').notNull(),
}, (table) => [
  /** Composite index for querying daily rollups by server within a time range */
  index('idx_daily_server_time').on(table.serverId, table.dayTimestamp),
]);
